---
   # Workaround for epel bug on CentOS 7.3 - https://bugs.centos.org/view.php?id=13669&nbn=1
   - name: Install http parser
     yum:
       name: "https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm"
       state: present

   - name: Install npm
     yum: name=npm state=present

   - name: Upgrade npm to latest version
     npm: name=n global=yes

   - name: Upgrade npm to latest version
     shell: n stable

   - name: Install Elasticdump
     npm: name=elasticdump global=yes

   - name: Load a single twitter message into the Twitter Index
     shell: elasticdump --input={{playbook_dir}}/elasticsearch_dataset/tweet.json --output=http://localhost:9200/twitter --type=data

   - name: Insert the dashboard
     script: "{{playbook_dir}}/elasticsearch_dataset/insert_dashboard.sh {{kibana_version}} {{kibana_build}}"

