---
   - name: Download Elasticsearch
     get_url:
       url: "{{elasticsearch_download_url}}"
       dest: "{{elasticsearch_download_location}}/elasticsearch-{{elasticsearch_version}}.rpm"
       timeout: 900

   - name: Install Elasticsearch
     yum: name={{elasticsearch_download_location}}/elasticsearch-{{elasticsearch_version}}.rpm state=present

   - name: Allow Elasticsearch to bind to all IP addresses
     vars:
       networkbindhost: 'network.bind_host: 0.0.0.0'
     lineinfile: dest=/etc/elasticsearch/elasticsearch.yml line='{{ networkbindhost }}' state=present

   - name: CentOS6 Disable system_call_filter
     vars:
       systemcallfilter: 'bootstrap.system_call_filter: false'
     lineinfile: dest=/etc/elasticsearch/elasticsearch.yml line='{{ systemcallfilter }}' state=present
     when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "6" 

   - name: Set ulimit nproc to 2048 for user elasticsearch
     vars:
       nproc: 'elasticsearch - nproc 2048'
     lineinfile: dest=/etc/security/limits.conf line='{{ nproc }}' state=present

   - name: Start the Elasticsearch service
     service:
       name: elasticsearch
       state: restarted
       enabled: yes

#   - name: Wait for Elasticsearch to come up
#     wait_for:
#       port: "{{elasticsearch_port}}"
#       delay: 5
